_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 2
                - 3
                - 12
                - 45
                - 50
                - 55
            "2":
                - 2
                - 3
                - 12
                - 45
                - 50
                - 55
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
encoder:
    value: '{''encoder_dim'': 256, ''num_encoder_layers'': 2, ''learning_rate'': 0.0001, ''tabulate'': False}'
env:
    value: '{''backend'': ''dmc'', ''env_id'': ''dog-run'', ''num_envs'': 4, ''utd_ratio'': 0.5, ''asynchronous'': True, ''dmc'': {''obs_type'': ''state''}}'
log_interval_steps:
    value: 10000
max_steps:
    value: 1000000
save_interval_steps:
    value: 100000
seed:
    value: 0
tdmpc2:
    value: '{''mpc'': True, ''horizon'': 3, ''mppi_iterations'': 6, ''population_size'': 512, ''policy_prior_samples'': 24, ''num_elites'': 64, ''min_plan_std'': 0.05, ''max_plan_std'': 2, ''temperature'': 0.5, ''batch_size'': 256, ''discount'': 0.99, ''rho'': 0.5, ''consistency_coef'': 20, ''reward_coef'': 0.1, ''continue_coef'': 1.0, ''value_coef'': 0.1, ''entropy_coef'': 0.0001, ''tau'': 0.01}'
wandb:
    value: '{''log_wandb'': True, ''project'': ''po-mpc development''}'
world_model:
    value: '{''mlp_dim'': 512, ''latent_dim'': 512, ''value_dropout'': 0.01, ''num_value_nets'': 5, ''num_bins'': 101, ''symlog_min'': -10, ''symlog_max'': 10, ''symlog_obs'': False, ''simnorm_dim'': 8, ''learning_rate'': 0.0003, ''predict_continues'': False, ''dtype'': ''float32'', ''max_grad_norm'': 20, ''tabulate'': False}'
