_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 2
                - 3
                - 12
                - 45
                - 50
                - 55
            "2":
                - 2
                - 3
                - 12
                - 45
                - 50
                - 55
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
